/* Automatically generated by po2tbl.sed from grun.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Choose Application", 2},
  {"\
gRun launches applications under X\n\
\n\
Usage grun [options] [file options]\n\
\n\
   file options     Launch file directly, no dialog boxes\n\
   --persist        Dialog persistance\n\
   --preload file   Load file as default command\n\
   --notips         Disable tooltips\n\
   --version        Show version\n\
   --help           Show this guide \n\
\n\
Copyright Southern Gold Development 1998\n", 3},
  {"\
gRun version %s\n\
\n\
Copyright Southern Gold Development 1998\n", 4},
  {"gRun %s", 5},
  {"Launch Application", 6},
  {"OK", 7},
  {"Launch application", 8},
  {"The OK button launches the application given in the entry box", 9},
  {"Close", 10},
  {"Cancel", 11},
  {"Close gRun", 12},
  {"The Close button will close the persistant gRun window", 13},
  {"Cancel launch", 14},
  {"The Cancel button cancels the launch process and closes gRun", 15},
  {"Browse", 16},
  {"Browse for command", 17},
  {"\
The Browse button opens a file selection box so the user can browse for the \
command to launch", 18},
};

int _msg_tbl_length = 18;
